/*
 * Variation Services
 * Services for variation data processing<p> <div style=\"font-size:1.1em;font-weight:normal\">NOTE: This service is still in beta testing mode. Please limit your request rate to 1 request/second.  dbSNP provides bulk download in VCF and JSON on the <a href=\"ftp://ftp.ncbi.nih.gov/snp/latest_release/\">FTP site</a> for users with a large number of RefSNPs (>100K) to process.</div> 
 *
 * OpenAPI spec version: 2.0.0
 * Contact: variation-services@ncbi.nlm.nih.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.pharmgkb.io.ncbi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;

/**
 * An organization outside of dbSNP will also accession variants and annotation.  This object provides the name of that organization, and associated accession.  The organization together with the accession provide a globally unique identifier.
 */
@Schema(description = "An organization outside of dbSNP will also accession variants and annotation.  This object provides the name of that organization, and associated accession.  The organization together with the accession provide a globally unique identifier.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-04-25T10:32:24.325-07:00[America/Los_Angeles]")public class ExternalRef {

  @SerializedName("organization")
  private String organization = null;

  @SerializedName("accession")
  private String accession = null;
  public ExternalRef organization(String organization) {
    this.organization = organization;
    return this;
  }

  

  /**
  * The name of the organization that has provided an accession
  * @return organization
  **/
  @Schema(required = true, description = "The name of the organization that has provided an accession")
  public String getOrganization() {
    return organization;
  }
  public void setOrganization(String organization) {
    this.organization = organization;
  }
  public ExternalRef accession(String accession) {
    this.accession = accession;
    return this;
  }

  

  /**
  * The accession provided by the organization
  * @return accession
  **/
  @Schema(required = true, description = "The accession provided by the organization")
  public String getAccession() {
    return accession;
  }
  public void setAccession(String accession) {
    this.accession = accession;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExternalRef externalRef = (ExternalRef) o;
    return Objects.equals(this.organization, externalRef.organization) &&
        Objects.equals(this.accession, externalRef.accession);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(organization, accession);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExternalRef {\n");
    
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    accession: ").append(toIndentedString(accession)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
