/*
 * Variation Services
 * Services for variation data processing<p> <div style=\"font-size:1.1em;font-weight:normal\">NOTE: This service is still in beta testing mode. Please limit your request rate to 1 request/second.  dbSNP provides bulk download in VCF and JSON on the <a href=\"ftp://ftp.ncbi.nih.gov/snp/latest_release/\">FTP site</a> for users with a large number of RefSNPs (>100K) to process.</div> 
 *
 * OpenAPI spec version: 2.0.0
 * Contact: variation-services@ncbi.nlm.nih.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.pharmgkb.io.ncbi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.pharmgkb.io.ncbi.model.Spdis;

/**
 * The input HGVS paired with its of result collection, which has one item per allele.
 */
@Schema(description = "The input HGVS paired with its of result collection, which has one item per allele.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-04-25T10:32:24.325-07:00[America/Los_Angeles]")public class HgvsBatchItem {

  @SerializedName("hgvs")
  private String hgvs = null;

  @SerializedName("alleles")
  private Spdis alleles = null;
  public HgvsBatchItem hgvs(String hgvs) {
    this.hgvs = hgvs;
    return this;
  }

  

  /**
  * the input HGVS expression
  * @return hgvs
  **/
  @Schema(required = true, description = "the input HGVS expression")
  public String getHgvs() {
    return hgvs;
  }
  public void setHgvs(String hgvs) {
    this.hgvs = hgvs;
  }
  public HgvsBatchItem alleles(Spdis alleles) {
    this.alleles = alleles;
    return this;
  }

  

  /**
  * Get alleles
  * @return alleles
  **/
  @Schema(required = true, description = "")
  public Spdis getAlleles() {
    return alleles;
  }
  public void setAlleles(Spdis alleles) {
    this.alleles = alleles;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HgvsBatchItem hgvsBatchItem = (HgvsBatchItem) o;
    return Objects.equals(this.hgvs, hgvsBatchItem.hgvs) &&
        Objects.equals(this.alleles, hgvsBatchItem.alleles);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(hgvs, alleles);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HgvsBatchItem {\n");
    
    sb.append("    hgvs: ").append(toIndentedString(hgvs)).append("\n");
    sb.append("    alleles: ").append(toIndentedString(alleles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
