/*
 * Variation Services
 * Services for variation data processing<p> <div style=\"font-size:1.1em;font-weight:normal\">NOTE: This service is still in beta testing mode. Please limit your request rate to 1 request/second.  dbSNP provides bulk download in VCF and JSON on the <a href=\"ftp://ftp.ncbi.nih.gov/snp/latest_release/\">FTP site</a> for users with a large number of RefSNPs (>100K) to process.</div> 
 *
 * OpenAPI spec version: 2.0.0
 * Contact: variation-services@ncbi.nlm.nih.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.pharmgkb.io.ncbi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.pharmgkb.io.ncbi.model.Allele;

/**
 * Description of a particular allele on a paritcular sequence
 */
@Schema(description = "Description of a particular allele on a paritcular sequence")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-04-25T10:32:24.325-07:00[America/Los_Angeles]")public class PlacementAnnotatedAllele {

  @SerializedName("allele")
  private Allele allele = null;

  @SerializedName("hgvs")
  private String hgvs = null;
  public PlacementAnnotatedAllele allele(Allele allele) {
    this.allele = allele;
    return this;
  }

  

  /**
  * Get allele
  * @return allele
  **/
  @Schema(required = true, description = "")
  public Allele getAllele() {
    return allele;
  }
  public void setAllele(Allele allele) {
    this.allele = allele;
  }
  public PlacementAnnotatedAllele hgvs(String hgvs) {
    this.hgvs = hgvs;
    return this;
  }

  

  /**
  * The HGVS expression for this allele on this placement
  * @return hgvs
  **/
  @Schema(required = true, description = "The HGVS expression for this allele on this placement")
  public String getHgvs() {
    return hgvs;
  }
  public void setHgvs(String hgvs) {
    this.hgvs = hgvs;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlacementAnnotatedAllele placementAnnotatedAllele = (PlacementAnnotatedAllele) o;
    return Objects.equals(this.allele, placementAnnotatedAllele.allele) &&
        Objects.equals(this.hgvs, placementAnnotatedAllele.hgvs);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(allele, hgvs);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlacementAnnotatedAllele {\n");
    
    sb.append("    allele: ").append(toIndentedString(allele)).append("\n");
    sb.append("    hgvs: ").append(toIndentedString(hgvs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
