/*
 * Variation Services
 * Services for variation data processing<p> <div style=\"font-size:1.1em;font-weight:normal\">NOTE: This service is still in beta testing mode. Please limit your request rate to 1 request/second.  dbSNP provides bulk download in VCF and JSON on the <a href=\"ftp://ftp.ncbi.nih.gov/snp/latest_release/\">FTP site</a> for users with a large number of RefSNPs (>100K) to process.</div> 
 *
 * OpenAPI spec version: 2.0.0
 * Contact: variation-services@ncbi.nlm.nih.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.pharmgkb.io.ncbi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.pharmgkb.io.ncbi.model.ProteinVariant;
import org.pharmgkb.io.ncbi.model.SoTerm;

/**
 * Represents the manifestation of a particular allele on a particular protein
 */
@Schema(description = "Represents the manifestation of a particular allele on a particular protein")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-04-25T10:32:24.325-07:00[America/Los_Angeles]")public class ProteinAnnotForAllele {

  @SerializedName("variant")
  private ProteinVariant variant = null;

  @SerializedName("sequence_ontology")
  private List<SoTerm> sequenceOntology = new ArrayList<SoTerm>();
  public ProteinAnnotForAllele variant(ProteinVariant variant) {
    this.variant = variant;
    return this;
  }

  

  /**
  * Get variant
  * @return variant
  **/
  @Schema(required = true, description = "")
  public ProteinVariant getVariant() {
    return variant;
  }
  public void setVariant(ProteinVariant variant) {
    this.variant = variant;
  }
  public ProteinAnnotForAllele sequenceOntology(List<SoTerm> sequenceOntology) {
    this.sequenceOntology = sequenceOntology;
    return this;
  }

  public ProteinAnnotForAllele addSequenceOntologyItem(SoTerm sequenceOntologyItem) {
    this.sequenceOntology.add(sequenceOntologyItem);
    return this;
  }

  /**
  * The description the protein consequence of this variant
  * @return sequenceOntology
  **/
  @Schema(required = true, description = "The description the protein consequence of this variant")
  public List<SoTerm> getSequenceOntology() {
    return sequenceOntology;
  }
  public void setSequenceOntology(List<SoTerm> sequenceOntology) {
    this.sequenceOntology = sequenceOntology;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProteinAnnotForAllele proteinAnnotForAllele = (ProteinAnnotForAllele) o;
    return Objects.equals(this.variant, proteinAnnotForAllele.variant) &&
        Objects.equals(this.sequenceOntology, proteinAnnotForAllele.sequenceOntology);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(variant, sequenceOntology);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProteinAnnotForAllele {\n");
    
    sb.append("    variant: ").append(toIndentedString(variant)).append("\n");
    sb.append("    sequenceOntology: ").append(toIndentedString(sequenceOntology)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
