/*
 * Variation Services
 * Services for variation data processing<p> <div style=\"font-size:1.1em;font-weight:normal\">NOTE: This service is still in beta testing mode. Please limit your request rate to 1 request/second.  dbSNP provides bulk download in VCF and JSON on the <a href=\"ftp://ftp.ncbi.nih.gov/snp/latest_release/\">FTP site</a> for users with a large number of RefSNPs (>100K) to process.</div> 
 *
 * OpenAPI spec version: 2.0.0
 * Contact: variation-services@ncbi.nlm.nih.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.pharmgkb.io.ncbi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;

/**
 * Nucleotide and amino acid changes are catagorized into Sequence Ontology terms.  For more information, see https://www.ncbi.nlm.nih.gov/variation/docs/glossary/
 */
@Schema(description = "Nucleotide and amino acid changes are catagorized into Sequence Ontology terms.  For more information, see https://www.ncbi.nlm.nih.gov/variation/docs/glossary/")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-04-25T10:32:24.325-07:00[America/Los_Angeles]")public class SoTerm {

  @SerializedName("name")
  private String name = null;

  @SerializedName("accession")
  private String accession = null;
  public SoTerm name(String name) {
    this.name = name;
    return this;
  }

  

  /**
  * The name of the SO-term
  * @return name
  **/
  @Schema(example = "insertion", required = true, description = "The name of the SO-term")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }
  public SoTerm accession(String accession) {
    this.accession = accession;
    return this;
  }

  

  /**
  * The accession of the SO-term
  * @return accession
  **/
  @Schema(example = "SO:0000667", required = true, description = "The accession of the SO-term")
  public String getAccession() {
    return accession;
  }
  public void setAccession(String accession) {
    this.accession = accession;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SoTerm soTerm = (SoTerm) o;
    return Objects.equals(this.name, soTerm.name) &&
        Objects.equals(this.accession, soTerm.accession);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(name, accession);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SoTerm {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    accession: ").append(toIndentedString(accession)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
