/*
 * Variation Services
 * Services for variation data processing<p> <div style=\"font-size:1.1em;font-weight:normal\">NOTE: This service is still in beta testing mode. Please limit your request rate to 1 request/second.  dbSNP provides bulk download in VCF and JSON on the <a href=\"ftp://ftp.ncbi.nih.gov/snp/latest_release/\">FTP site</a> for users with a large number of RefSNPs (>100K) to process.</div> 
 *
 * OpenAPI spec version: 2.0.0
 * Contact: variation-services@ncbi.nlm.nih.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.pharmgkb.io.ncbi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.pharmgkb.io.ncbi.model.Error;
import org.pharmgkb.io.ncbi.model.Spdi;
import org.pharmgkb.io.ncbi.model.Warnings;

/**
 * A set of contextual alleles in SPDI notation. Order is not significant. There may be duplicates.
 */
@Schema(description = "A set of contextual alleles in SPDI notation. Order is not significant. There may be duplicates.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-04-25T10:32:24.325-07:00[America/Los_Angeles]")public class Spdis {

  @SerializedName("spdis")
  private List<Spdi> spdis = new ArrayList<Spdi>();

  @SerializedName("errors")
  private Error errors = null;

  @SerializedName("warnings")
  private Warnings warnings = null;
  public Spdis spdis(List<Spdi> spdis) {
    this.spdis = spdis;
    return this;
  }

  public Spdis addSpdisItem(Spdi spdisItem) {
    this.spdis.add(spdisItem);
    return this;
  }

  /**
  * Get spdis
  * @return spdis
  **/
  @Schema(required = true, description = "")
  public List<Spdi> getSpdis() {
    return spdis;
  }
  public void setSpdis(List<Spdi> spdis) {
    this.spdis = spdis;
  }
  public Spdis errors(Error errors) {
    this.errors = errors;
    return this;
  }

  

  /**
  * Get errors
  * @return errors
  **/
  @Schema(description = "")
  public Error getErrors() {
    return errors;
  }
  public void setErrors(Error errors) {
    this.errors = errors;
  }
  public Spdis warnings(Warnings warnings) {
    this.warnings = warnings;
    return this;
  }

  

  /**
  * Get warnings
  * @return warnings
  **/
  @Schema(description = "")
  public Warnings getWarnings() {
    return warnings;
  }
  public void setWarnings(Warnings warnings) {
    this.warnings = warnings;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Spdis spdis = (Spdis) o;
    return Objects.equals(this.spdis, spdis.spdis) &&
        Objects.equals(this.errors, spdis.errors) &&
        Objects.equals(this.warnings, spdis.warnings);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(spdis, errors, warnings);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Spdis {\n");
    
    sb.append("    spdis: ").append(toIndentedString(spdis)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    warnings: ").append(toIndentedString(warnings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
