/*
 * Variation Services
 * Services for variation data processing<p> <div style=\"font-size:1.1em;font-weight:normal\">NOTE: This service is still in beta testing mode. Please limit your request rate to 1 request/second.  dbSNP provides bulk download in VCF and JSON on the <a href=\"ftp://ftp.ncbi.nih.gov/snp/latest_release/\">FTP site</a> for users with a large number of RefSNPs (>100K) to process.</div> 
 *
 * OpenAPI spec version: 2.0.0
 * Contact: variation-services@ncbi.nlm.nih.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.pharmgkb.io.ncbi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.pharmgkb.io.ncbi.model.SupportId;

/**
 * Record of a submission that supports this RefSNPs.  RefSNPs are insantiated when a variant submission exists at the RefSNP&#x27;s location and type (aka anchor).
 */
@Schema(description = "Record of a submission that supports this RefSNPs.  RefSNPs are insantiated when a variant submission exists at the RefSNP's location and type (aka anchor).")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-04-25T10:32:24.325-07:00[America/Los_Angeles]")public class Support {

  @SerializedName("id")
  private SupportId id = null;

  @SerializedName("revision_added")
  private String revisionAdded = null;

  @SerializedName("create_date")
  private String createDate = null;

  @SerializedName("submitter_handle")
  private String submitterHandle = null;
  public Support id(SupportId id) {
    this.id = id;
    return this;
  }

  

  /**
  * Get id
  * @return id
  **/
  @Schema(required = true, description = "")
  public SupportId getId() {
    return id;
  }
  public void setId(SupportId id) {
    this.id = id;
  }
  public Support revisionAdded(String revisionAdded) {
    this.revisionAdded = revisionAdded;
    return this;
  }

  

  /**
  * The revision in which this support was added to this RefSNP
  * @return revisionAdded
  **/
  @Schema(required = true, description = "The revision in which this support was added to this RefSNP")
  public String getRevisionAdded() {
    return revisionAdded;
  }
  public void setRevisionAdded(String revisionAdded) {
    this.revisionAdded = revisionAdded;
  }
  public Support createDate(String createDate) {
    this.createDate = createDate;
    return this;
  }

  

  /**
  * The date this support was added to this RefSNP
  * @return createDate
  **/
  @Schema(example = "2001-01-15T00:00Z", required = true, description = "The date this support was added to this RefSNP")
  public String getCreateDate() {
    return createDate;
  }
  public void setCreateDate(String createDate) {
    this.createDate = createDate;
  }
  public Support submitterHandle(String submitterHandle) {
    this.submitterHandle = submitterHandle;
    return this;
  }

  

  /**
  * The unique, dbSNP-registered name of the submitter
  * @return submitterHandle
  **/
  @Schema(required = true, description = "The unique, dbSNP-registered name of the submitter")
  public String getSubmitterHandle() {
    return submitterHandle;
  }
  public void setSubmitterHandle(String submitterHandle) {
    this.submitterHandle = submitterHandle;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Support support = (Support) o;
    return Objects.equals(this.id, support.id) &&
        Objects.equals(this.revisionAdded, support.revisionAdded) &&
        Objects.equals(this.createDate, support.createDate) &&
        Objects.equals(this.submitterHandle, support.submitterHandle);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, revisionAdded, createDate, submitterHandle);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Support {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    revisionAdded: ").append(toIndentedString(revisionAdded)).append("\n");
    sb.append("    createDate: ").append(toIndentedString(createDate)).append("\n");
    sb.append("    submitterHandle: ").append(toIndentedString(submitterHandle)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
