/*
 * Variation Services
 * Services for variation data processing<p> <div style=\"font-size:1.1em;font-weight:normal\">NOTE: This service is still in beta testing mode. Please limit your request rate to 1 request/second.  dbSNP provides bulk download in VCF and JSON on the <a href=\"ftp://ftp.ncbi.nih.gov/snp/latest_release/\">FTP site</a> for users with a large number of RefSNPs (>100K) to process.</div> 
 *
 * OpenAPI spec version: 2.0.0
 * Contact: variation-services@ncbi.nlm.nih.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.pharmgkb.io.ncbi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.pharmgkb.io.ncbi.model.Support;

/**
 * Data specific to withdrawn snapshots
 */
@Schema(description = "Data specific to withdrawn snapshots")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-04-25T10:32:24.325-07:00[America/Los_Angeles]")public class WithdrawnSnapshotData {

  @SerializedName("withdrawn_time")
  private String withdrawnTime = null;

  @SerializedName("support")
  private List<Support> support = new ArrayList<Support>();
  public WithdrawnSnapshotData withdrawnTime(String withdrawnTime) {
    this.withdrawnTime = withdrawnTime;
    return this;
  }

  

  /**
  * The date and time this RefSnp was withdrawn
  * @return withdrawnTime
  **/
  @Schema(example = "2001-01-15T00:00Z", required = true, description = "The date and time this RefSnp was withdrawn")
  public String getWithdrawnTime() {
    return withdrawnTime;
  }
  public void setWithdrawnTime(String withdrawnTime) {
    this.withdrawnTime = withdrawnTime;
  }
  public WithdrawnSnapshotData support(List<Support> support) {
    this.support = support;
    return this;
  }

  public WithdrawnSnapshotData addSupportItem(Support supportItem) {
    this.support.add(supportItem);
    return this;
  }

  /**
  * The observations that support the existence of a variant at this particular location and type. Supporting observations can come from submissions to dbSNP or from external data sources like ClinVar.
  * @return support
  **/
  @Schema(required = true, description = "The observations that support the existence of a variant at this particular location and type. Supporting observations can come from submissions to dbSNP or from external data sources like ClinVar.")
  public List<Support> getSupport() {
    return support;
  }
  public void setSupport(List<Support> support) {
    this.support = support;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WithdrawnSnapshotData withdrawnSnapshotData = (WithdrawnSnapshotData) o;
    return Objects.equals(this.withdrawnTime, withdrawnSnapshotData.withdrawnTime) &&
        Objects.equals(this.support, withdrawnSnapshotData.support);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(withdrawnTime, support);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WithdrawnSnapshotData {\n");
    
    sb.append("    withdrawnTime: ").append(toIndentedString(withdrawnTime)).append("\n");
    sb.append("    support: ").append(toIndentedString(support)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
