/*
 * Variation Services
 * Services for variation data processing<p> <div style=\"font-size:1.1em;font-weight:normal\">NOTE: This service is still in beta testing mode. Please limit your request rate to 1 request/second.  dbSNP provides bulk download in VCF and JSON on the <a href=\"ftp://ftp.ncbi.nih.gov/snp/latest_release/\">FTP site</a> for users with a large number of RefSNPs (>100K) to process.</div> 
 *
 * OpenAPI spec version: 2.0.0
 * Contact: variation-services@ncbi.nlm.nih.gov
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.pharmgkb.io.ncbi.api;

import org.pharmgkb.io.ncbi.ApiException;
import org.pharmgkb.io.ncbi.model.Error;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FrequencyNotYetAvailableComingSoonApi
 */
@Ignore
public class FrequencyNotYetAvailableComingSoonApiTest {

    private final FrequencyNotYetAvailableComingSoonApi api = new FrequencyNotYetAvailableComingSoonApi();

    /**
     * Retrieve frequencies for variants overlapping a position range
     *
     * Retrieve frequencies for variants whose Contextual SPDI overlaps the sequence interval in the query. Detailed information about ids used in reply could be retrieved using \&quot;/metadata/frequency\&quot; endpoint. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void frequencyByIntervalTest() throws ApiException {
        String seqId = null;
        Integer position = null;
        Integer length = null;
        Object response = api.frequencyByInterval(seqId, position, length);

        // TODO: test validations
    }
    /**
     * Retrieve frequency metadata
     *
     * Retrieve information that describes all studies and populations used by frequency endpoint.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void frequencyMetadataTest() throws ApiException {
        Map response = api.frequencyMetadata();

        // TODO: test validations
    }
}
